version: "3.1"

services:
  bot:
    build: "./bot"
    depends_on:
      - mongo
    tty: true
    environment:
      SERVICE_ID: ${SERVICE_ID}
      TOKEN_ADDRESS: ${TOKEN_ADDRESS}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      SYMBOL: ${SYMBOL}

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: user
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
